FROM eclipse-temurin:8

WORKDIR /build
ADD https://github.com/sbt/sbt/releases/download/v1.7.3/sbt-1.7.3.tgz .
RUN tar -xzf sbt-1.7.3.tgz

COPY build.sbt .
COPY project project
COPY src src
COPY core core
COPY producer producer
RUN sbt/bin/sbt producer/compile
CMD [ "sbt/bin/sbt", "producer/run rabbitmq raw 1000" ]